name: model-training-and-reporting

# Trigger on pull request events (opened, synchronized/pushed to)
on: [pull_request] # <--- CHANGE THIS LINE

jobs:
  train-and-report:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    permissions:
      contents: write      # Needed to checkout code and potentially for CML internals
      pull-requests: write # Needed specifically to post comments on PRs

    steps:
      # Check out the repository code associated with the PR
      - uses: actions/checkout@v3
        # Fetch depth 0 is often recommended for PRs to ensure CML/DVC
        # can compare against the base branch if needed, though not
        # strictly required for just posting a comment.
        with:
          fetch-depth: 0

      # Step 1: Train the model
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          # Create output directory if it doesn't exist (good practice)
          mkdir -p output
          python train.py

      # Step 2: Create CML report
      - name: Create CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Create a markdown report file (report.md)
          echo "## Model Metrics" >> report.md
          echo '```' >> report.md
          cat output/metrics.txt >> report.md
          echo '```' >> report.md

          echo "## Feature Importances" >> report.md
          echo "![Feature Importances](output/feature_importances.png)" >> report.md

          echo "## Residuals Plot" >> report.md
          echo "![Residuals Plot](output/residuals_plot.png)" >> report.md

          # Publish the report to the PR comment
          cml comment create report.md
