name: model-training-and-reporting
on: [push]
jobs:
  train-and-report:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          python train.py  # generate plot.png

          echo "## Model Metrics" > report.md
          cat output/metrics.txt >> report.md

          echo "## Model Metrics" > report.md
          cat output/metrics.txt >> report.md

          echo "## Data Visualization" >> report.md
          echo "![Feature Importances](output/feature_importances.png)" >> report.md
          echo "![Residuals Plot](output/residuals_plot.png)" >> report.md

          # Corrected `cml comment create` command
          cml comment create --commit-sha $GITHUB_SHA --pr --markdown-file report.md

          