name: model-training-and-reporting

# This workflow runs on every push to any branch
on: [push]

jobs:
  train-and-report:
    runs-on: ubuntu-latest
    # Use a CML-provided Docker image with necessary tools
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1

    # <<<--- ADD THIS PERMISSIONS BLOCK --- >>>
    permissions:
      contents: write # Required to post commit comments

    steps:
      # Check out the repository code
      - uses: actions/checkout@v3

    # Mark repository as safe
      - name: Mark repository as safe
        run: git config --global --add safe.directory /__w/automl_project1/automl_project1
      - name: CML RUN
        # Set the GITHUB_TOKEN environment variable (still good practice)
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Install Python dependencies
          pip install -r requirements.txt
          dvc repro

          git fetch --prune
          # dvc metrics diff  --show-md compare-ml-model1 > report.md
          dvc metrics diff compare-ml-model1 --targets metrics.json --show-md >> report.md

          # Add figure to the report
          echo "## Data Visualization"

          echo "![LinearRegression Actual vs Predicted](plots/LinearRegression_actual_vs_predicted.png)" >> report.md
          echo "![Ridge Actual vs Predicted](plots/Ridge_actual_vs_predicted.png)" >> report.md
          echo "![Lasso Actual vs Predicted](plots/Lasso_actual_vs_predicted.png)" >> report.md
          echo "![RandomForest Actual vs Predicted](plots/RandomForest_actual_vs_predicted.png)" >> report.md
          echo "![LinearRegression Residual Plot](plots/LinearRegression_residual_plot.png)" >> report.md
          echo "![Ridge Residual Plot](plots/Ridge_residual_plot.png)" >> report.md
          echo "![Lasso Residual Plot](plots/Lasso_residual_plot.png)" >> report.md
          echo "![RandomForest Residual Plot](plots/RandomForest_residual_plot.png)" >> report.md
          
          echo "## Prediction Results"

          echo "![predictions_LinearRegression.png](plots/predictions_LinearRegression.png)" >> report.md
          echo "![predictions_Ridge.png](plots/predictions_Ridge.png)" >> report.md
          echo "![predictions_Lasso.png](plots/predictions_Lasso.png)" >> report.md
          echo "![predictions_RandomForest.png](plots/predictions_RandomForest.png)" >> report.md
          echo "![predictions_all_models.png](plots/predictions_all_models.png)" >> report.md

          cml comment create report.md


